/**
 * Vanilla Minecraft Block Colors
 *
 * This file contains all vanilla blocks that support biome-based color tinting.
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by scraping the Minecraft Wiki.
 *
 * Generation info:
 * - Source: https://minecraft.wiki/w/Block_colors
 * - Generated: 2025-11-24T19:34:04.568Z
 * - Script: scripts/scrapeMinecraftColors.ts
 *
 * To regenerate: npm run generate:colors
 */

/**
 * Blocks that use the grass.png colormap
 */
export const GRASS_TINTED_BLOCKS = [
  "minecraft:attached_melon_stem",
  "minecraft:attached_pumpkin_stem",
  "minecraft:fern",
  "minecraft:grass",
  "minecraft:grass_block",
  "minecraft:large_fern",
  "minecraft:lily_pad",
  "minecraft:melon_stem",
  "minecraft:pink_petals",
  "minecraft:potted_fern",
  "minecraft:pumpkin_stem",
  "minecraft:short_grass",
  "minecraft:sugar_cane",
  "minecraft:tall_grass",
] as const;

/**
 * Blocks that use the foliage.png colormap
 */
export const FOLIAGE_TINTED_BLOCKS = [
  "minecraft:acacia_leaves",
  "minecraft:dark_oak_leaves",
  "minecraft:jungle_leaves",
  "minecraft:mangrove_leaves",
  "minecraft:oak_leaves",
  "minecraft:vine",
] as const;

/**
 * Blocks that use water colormap
 */
export const WATER_TINTED_BLOCKS = [
  "minecraft:bubble_column",
  "minecraft:flowing_water",
  "minecraft:water",
  "minecraft:water_cauldron",
] as const;

/**
 * Blocks with special/custom tinting logic
 */
export const SPECIAL_TINTED_BLOCKS = [
  "minecraft:bamboo",
  "minecraft:bamboo_sapling",
  "minecraft:redstone_wire",
] as const;

/**
 * Blocks with fixed colors (NOT biome-dependent)
 */
export const FIXED_COLOR_BLOCKS = [
  "minecraft:azalea_leaves",
  "minecraft:birch_leaves",
  "minecraft:cherry_leaves",
  "minecraft:flowering_azalea_leaves",
  "minecraft:spruce_leaves",
] as const;

export type TintType = "grass" | "foliage" | "water" | "special";

/**
 * Get the tint type for a block ID.
 */
export function getBlockTintType(blockId: string): TintType | undefined {
  if (GRASS_TINTED_BLOCKS.includes(blockId as any)) return "grass";
  if (FOLIAGE_TINTED_BLOCKS.includes(blockId as any)) return "foliage";
  if (WATER_TINTED_BLOCKS.includes(blockId as any)) return "water";
  if (SPECIAL_TINTED_BLOCKS.includes(blockId as any)) return "special";
  return undefined;
}

export const BLOCK_COLORS_METADATA = {
  source: "https://minecraft.wiki/w/Block_colors",
  generatedAt: "2025-11-24T19:34:04.568Z",
  totalBlocks: 27,
} as const;
