/**
 * Vanilla Minecraft Block Colors
 *
 * This file contains all vanilla blocks that support biome-based color tinting.
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * This file is automatically generated by scraping the Minecraft Wiki.
 *
 * Generation info:
 * - Source: https://minecraft.wiki/w/Block_colors
 * - Generated: 2025-11-20T19:45:22.032Z
 * - Script: scripts/scrapeBlockColors.ts
 *
 * To regenerate:
 *   npm run generate:blockcolors
 */

/**
 * Blocks that use the grass.png colormap
 * These blocks change color based on biome grass color.
 */
export const GRASS_TINTED_BLOCKS = [
  "minecraft:attached_melon_stem",
  "minecraft:attached_pumpkin_stem",
  "minecraft:fern",
  "minecraft:grass",
  "minecraft:grass_block",
  "minecraft:large_fern",
  "minecraft:lily_pad",
  "minecraft:melon_stem",
  "minecraft:pink_petals",
  "minecraft:potted_fern",
  "minecraft:pumpkin_stem",
  "minecraft:short_grass",
  "minecraft:sugar_cane",
  "minecraft:tall_grass",
] as const;

/**
 * Blocks that use the foliage.png colormap
 * These blocks change color based on biome foliage color.
 *
 * Note: Birch and Spruce leaves are NOT included as they have fixed colors.
 * Cherry and Azalea leaves also have fixed colors.
 */
export const FOLIAGE_TINTED_BLOCKS = [
  "minecraft:acacia_leaves",
  "minecraft:dark_oak_leaves",
  "minecraft:jungle_leaves",
  "minecraft:mangrove_leaves",
  "minecraft:oak_leaves",
  "minecraft:vine",
] as const;

/**
 * Blocks that use water colormap
 * These blocks change color based on biome water color.
 */
export const WATER_TINTED_BLOCKS = [
  "minecraft:bubble_column",
  "minecraft:flowing_water",
  "minecraft:water",
  "minecraft:water_cauldron",
] as const;

/**
 * Blocks with special/custom tinting logic
 * These don't use colormaps directly but have hardcoded color logic.
 */
export const SPECIAL_TINTED_BLOCKS = [
  "minecraft:bamboo",
  "minecraft:bamboo_sapling",
  "minecraft:redstone_wire",
] as const;

/**
 * Blocks with fixed colors (NOT biome-dependent)
 * These blocks have tintindex but don't change with biome.
 * Included here for completeness but should NOT be tinted by colormaps.
 */
export const FIXED_COLOR_BLOCKS = [
  "minecraft:azalea_leaves",
  "minecraft:birch_leaves",
  "minecraft:cherry_leaves",
  "minecraft:flowering_azalea_leaves",
  "minecraft:spruce_leaves",
] as const;

/**
 * All blocks that support any form of tinting
 */
export const ALL_TINTED_BLOCKS = [
  ...GRASS_TINTED_BLOCKS,
  ...FOLIAGE_TINTED_BLOCKS,
  ...WATER_TINTED_BLOCKS,
  ...SPECIAL_TINTED_BLOCKS,
] as const;

/**
 * Type for tint categories
 */
export type TintType = "grass" | "foliage" | "water" | "special";

/**
 * Get the tint type for a block ID.
 * Returns undefined if the block doesn't support biome-based tinting.
 *
 * Note: This only returns tint types for blocks that should use colormaps.
 * Blocks with fixed colors (birch_leaves, cherry_leaves, etc.) return undefined.
 *
 * @param blockId - Minecraft block ID (e.g., "minecraft:oak_leaves")
 * @returns Tint type or undefined
 */
export function getBlockTintType(blockId: string): TintType | undefined {
  if (GRASS_TINTED_BLOCKS.includes(blockId as any)) return "grass";
  if (FOLIAGE_TINTED_BLOCKS.includes(blockId as any)) return "foliage";
  if (WATER_TINTED_BLOCKS.includes(blockId as any)) return "water";
  if (SPECIAL_TINTED_BLOCKS.includes(blockId as any)) return "special";
  return undefined;
}

/**
 * Check if a block supports biome-based tinting.
 *
 * @param blockId - Minecraft block ID
 * @returns True if the block uses a colormap for tinting
 */
export function isBlockTinted(blockId: string): boolean {
  return getBlockTintType(blockId) !== undefined;
}

/**
 * Check if a block has a fixed color (has tintindex but doesn't change with biome).
 *
 * @param blockId - Minecraft block ID
 * @returns True if the block has fixed color
 */
export function hasFixedColor(blockId: string): boolean {
  return FIXED_COLOR_BLOCKS.includes(blockId as any);
}

/**
 * Metadata about this file
 */
export const BLOCK_COLORS_METADATA = {
  source: "https://minecraft.wiki/w/Block_colors",
  generatedAt: "2025-11-20T19:45:22.032Z",
  totalBlocks: 27,
  grassBlocks: 14,
  foliageBlocks: 6,
  waterBlocks: 4,
  specialBlocks: 3,
  fixedColorBlocks: 5,
} as const;
