/**
 * Movement-based animation presets
 */

import type { AnimationPreset } from "../animationPresets";

export const MOVEMENT_PRESETS: AnimationPreset[] = [
  {
    id: "idle",
    name: "Idle",
    description: "Stationary with breathing and ambient motion",
    icon: "🧍",
    duration: 0,
    loop: true,
    setup: () => ({
      limb_swing: 0,
      limb_speed: 0,
      swing_progress: 0,
      hurt_time: 0,
      death_time: 0,
      is_aggressive: false,
      is_hurt: false,
      is_sprinting: false,
      is_in_water: false,
      health: 20,
    }),
    update: (state, dt) => ({
      age: state.age + dt * 20,
      time: (state.time + dt * 20) % 27720,
      frame_time: dt,
      limb_swing: 0,
      limb_speed: 0,
    }),
  },

  {
    id: "walking",
    name: "Walking",
    description: "Normal walking motion",
    icon: "🚶",
    duration: 0,
    loop: true,
    setup: () => ({
      limb_speed: 0.4,
      swing_progress: 0,
      hurt_time: 0,
      death_time: 0,
      is_on_ground: true,
      is_sprinting: false,
      is_in_water: false,
      health: 20,
    }),
    update: (state, dt) => ({
      age: state.age + dt * 20,
      time: (state.time + dt * 20) % 27720,
      frame_time: dt,
      limb_swing: state.limb_swing + dt * 20 * state.limb_speed,
      limb_speed: 0.4,
      is_on_ground: true,
    }),
  },

  {
    id: "sprinting",
    name: "Sprinting",
    description: "Fast running motion",
    icon: "🏃",
    duration: 0,
    loop: true,
    setup: () => ({
      limb_speed: 1.0,
      swing_progress: 0,
      hurt_time: 0,
      death_time: 0,
      is_on_ground: true,
      is_sprinting: true,
      is_in_water: false,
      health: 20,
    }),
    update: (state, dt) => ({
      age: state.age + dt * 20,
      time: (state.time + dt * 20) % 27720,
      frame_time: dt,
      limb_swing: state.limb_swing + dt * 20 * state.limb_speed,
      limb_speed: 1.0,
      is_sprinting: true,
      is_on_ground: true,
    }),
  },

  {
    id: "swimming",
    name: "Swimming",
    description: "Swimming motion",
    icon: "🏊",
    duration: 0,
    loop: true,
    setup: () => ({
      is_in_water: true,
      is_on_ground: false,
      is_wet: true,
      hurt_time: 0,
      death_time: 0,
      health: 20,
    }),
    update: (state, dt) => ({
      age: state.age + dt * 20,
      time: (state.time + dt * 20) % 27720,
      frame_time: dt,
      limb_swing: state.limb_swing + dt * 20 * state.limb_speed,
      limb_speed: 0.6,
      is_in_water: true,
      is_on_ground: false,
      is_wet: true,
    }),
  },

  {
    id: "sneaking",
    name: "Sneaking",
    description: "Crouching/sneaking motion",
    icon: "🥷",
    duration: 0,
    loop: true,
    setup: () => ({
      is_sneaking: true,
      is_on_ground: true,
      hurt_time: 0,
      death_time: 0,
      health: 20,
    }),
    update: (state, dt) => ({
      age: state.age + dt * 20,
      time: (state.time + dt * 20) % 27720,
      frame_time: dt,
      limb_swing: state.limb_swing + dt * 20 * state.limb_speed,
      limb_speed: 0.25,
      is_sneaking: true,
      is_on_ground: true,
    }),
  },

  {
    id: "sitting",
    name: "Sitting",
    description: "Sitting/resting pose",
    icon: "🧘",
    duration: 0,
    loop: true,
    setup: () => ({
      is_sitting: true,
      is_on_ground: true,
      limb_speed: 0,
      limb_swing: 0,
      hurt_time: 0,
      death_time: 0,
      health: 20,
    }),
    update: (state, dt) => ({
      age: state.age + dt * 20,
      time: (state.time + dt * 20) % 27720,
      frame_time: dt,
      limb_swing: 0,
      limb_speed: 0,
      is_sitting: true,
    }),
  },

  {
    id: "riding",
    name: "Riding",
    description: "Mounted on another entity",
    icon: "🏇",
    duration: 0,
    loop: true,
    setup: () => ({
      is_riding: true,
      is_on_ground: false,
      hurt_time: 0,
      death_time: 0,
      health: 20,
    }),
    update: (state, dt) => ({
      age: state.age + dt * 20,
      time: (state.time + dt * 20) % 27720,
      frame_time: dt,
      limb_swing: state.limb_swing + dt * 20 * state.limb_speed,
      limb_speed: 0.3,
      is_riding: true,
      is_on_ground: false,
      pos_y: Math.sin(state.age / 10) * 0.1,
    }),
  },
];
